### ISSUE TITLE
Memory leak issue with pyplot

### ISSUE THREAD

**Issue by catEmperor** [rcompt/Fact-Feel-FlaskApp#40]
The way the UI is plotting is creating a brand new plot each time without cleaning up the previous one

**Comment by rcompt** [comment]
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.clf.html

We added this function to plot within factfeel_gui.py, need a more thorough test to verify this is actually helping. Compare running with it and without it

**Comment by rcompt** [comment]
New error after running for 20+ itertations
```
C:\Users\Stang\Documents\Projects\Fact-Feel-FlaskApp\factfeel_gui.py:140: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, ax = plt.subplots()
```
