### ISSUE TITLE
Determine UI library for both Windows and Linux 

### ISSUE THREAD

**Issue by rcompt** [rcompt/Fact-Feel-FlaskApp#6]
Find a library that is capable of functioning on both Windows and Linux

**Comment by rcompt** [comment]
https://platform.uno/

**Comment by rcompt** [comment]
https://visualstudiomagazine.com/articles/2021/01/05/maui.aspx

**Comment by catEmperor** [comment]
@rcompt can you provide the OS and architecture (x64, ARM, etc) information for your Raspberry Pi?

**Comment by catEmperor** [comment]
@rcompt I also want to know if this is a Raspberry Pi 3 or 4

**Comment by catEmperor** [comment]
The OS question may not answer since it's Raspbian. Don't know if there are version differences so I wanted to know just in case

**Comment by catEmperor** [comment]
@rcompt  I have a test for you. Check out to the ZT/ThirdPassUI_Avalonia branch, unzip the zip file _LinuxDeployment.zip, and run the "FactFeelView" file from the console/bash script on your raspberry pi and let me know if it runs

**Comment by rcompt** [comment]
Verified to be working!

**Comment by rcompt** [comment]
Closing issue
