### ISSUE TITLE
Investigate Speech-To-Text Streaming Rather A Sample-Based Approach

### ISSUE THREAD

**Issue by catEmperor** [rcompt/Fact-Feel-FlaskApp#60]

**Comment by catEmperor** [comment]
The way we use the speech recognition API is such that text converted from speech always represents a fragment of whatever was being spoken. If there is a way to more fluidly process incoming audio to text faster then we can get closer to being able to capture all audio spoken in a session

**Comment by rcompt** [comment]
https://github.com/tyiannak/pyAudioAnalysis

**Comment by rcompt** [comment]
Finished with merge
